version: '2'
services:
  database: 
    build: database/
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db/

  app:
    build: app/
    ports:
      - "8080:80"
    environment:
      - PORT=80
      - ROOT_URL=http://localhost/
      - MONGO_URL=mongodb://database/ccr
    depends_on:
      - database

  reciever:
    build: reciever/
    ports:
      - "5000:5000"
    environment:
      - CCR_SOURCE=tcp://*:5000
      - CCR_MONGO_URL=mongodb://database/ccr
    depends_on:
      - database
