version: '2'
services:
  database: 
    build: database/
    ports:
      - "27017:27017"
    # volumes:
    #   - database/db:/data/db/

  app:
    build: app/
    ports:
      - "8080:80"
    environment:
      - PORT=80
      - ROOT_URL=http://localhost/
      - MONGO_URL=mongodb://database:27017/
    depends_on:
      - database

