apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: ccr
    module: app
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    module: app
  type: LoadBalancer
