apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    app: ccr
    module: database
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/ccr-db/
