apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: ccr
    module: database
spec:
  ports:
    - port: 27017
  selector:
    app: ccr
    module: database
  # clusterIP: None
